const videos = [
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+1",
      profileUrl: "https://placehold.co/50x50?text=User+1",
      title: "Introduction to React",
      views: "1.2M",
      channelName: "Tech Guru",
      publishedDate: "2 weeks ago",
      duration: "12:45",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+2",
      profileUrl: "https://placehold.co/50x50?text=User+2",
      title: "JavaScript ES6 Features",
      views: "890K",
      channelName: "Code Academy",
      publishedDate: "1 month ago",
      duration: "9:30",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+3",
      profileUrl: "https://placehold.co/50x50?text=User+3",
      title: "Learn Tailwind CSS in 10 Minutes",
      views: "530K",
      channelName: "Design Hub",
      publishedDate: "3 weeks ago",
      duration: "10:15",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+4",
      profileUrl: "https://placehold.co/50x50?text=User+4",
      title: "Node.js Crash Course",
      views: "2M",
      channelName: "Backend Master",
      publishedDate: "5 months ago",
      duration: "15:20",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+5",
      profileUrl: "https://placehold.co/50x50?text=User+5",
      title: "How to Deploy a React App",
      views: "720K",
      channelName: "DevOps Simplified",
      publishedDate: "1 year ago",
      duration: "14:05",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+6",
      profileUrl: "https://placehold.co/50x50?text=User+6",
      title: "CSS Grid vs Flexbox",
      views: "950K",
      channelName: "CSS Mastery",
      publishedDate: "2 months ago",
      duration: "11:40",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+7",
      profileUrl: "https://placehold.co/50x50?text=User+7",
      title: "Python for Beginners",
      views: "1.8M",
      channelName: "Code with Python",
      publishedDate: "6 months ago",
      duration: "18:30",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+8",
      profileUrl: "https://placehold.co/50x50?text=User+8",
      title: "Kubernetes Basics",
      views: "450K",
      channelName: "Cloud Academy",
      publishedDate: "3 weeks ago",
      duration: "8:50",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+9",
      profileUrl: "https://placehold.co/50x50?text=User+9",
      title: "Mastering Git & GitHub",
      views: "680K",
      channelName: "GitHub Essentials",
      publishedDate: "4 months ago",
      duration: "13:15",
    },
    {
      thumbnail: "https://placehold.co/300x200?text=Thumbnail+10",
      profileUrl: "https://placehold.co/50x50?text=User+10",
      title: "Intro to Machine Learning",
      views: "1.5M",
      channelName: "AI Explained",
      publishedDate: "9 months ago",
      duration: "16:25",
    }
  ];
  
  export default videos;